# Generated by Django 5.1 on 2024-08-15 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_alter_amenity_options_alter_image_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenity',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
