# Generated by Django 5.1 on 2024-08-15 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_alter_amenity_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img_path',
            field=models.ImageField(max_length=255, upload_to='images/'),
        ),
    ]
