# Generated by Django 5.1 on 2024-08-15 09:52

import properties.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_alter_image_img_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img_path',
            field=models.ImageField(max_length=255, upload_to=properties.models.generate_image_filename),
        ),
    ]
