# Generated by Django 5.1 on 2024-08-16 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_alter_location_latitude_alter_location_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenity',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('name', 'type')},
        ),
    ]
