# Generated by Django 5.1 on 2024-08-16 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_alter_amenity_name_alter_location_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenity',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
