# Generated by Django 5.1 on 2024-08-16 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_alter_amenity_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('name', 'latitude', 'longitude')},
        ),
    ]
