# Generated by Django 5.1 on 2024-08-20 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0013_alter_amenity_updated_date_alter_image_updated_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenity',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='propertyinfo',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
