# Generated by Django 5.1 on 2024-08-22 09:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0015_alter_amenity_updated_date_alter_image_updated_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('summary', models.TextField()),
                ('property_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='properties.propertyinfo')),
            ],
            options={
                'verbose_name_plural': 'Property Summaries',
                'db_table': 'property_summary',
            },
        ),
    ]
